version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    depends_on:
      - backend

  backend:
    build:
      context: online-store-backend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - '8000:8000'
    volumes:
      - './online-store-backend:/var/www/html'
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=sail
      - DB_USERNAME=sail
      - DB_PASSWORD=password
